name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME


#      - name: Deploy to server
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USER }}
#          key: ${{ secrets.DEPLOY_SSH_KEY }}
#          script: |
#            docker pull ghcr.io/${{ github.repository }}:latest
#            docker stop fastapi-app || true
#            docker rm fastapi-app || true
#            docker run -d \
#              --name fastapi-app \
#              -p 8000:8000 \
#              ghcr.io/${{ github.repository }}:latest
